# Generated by Django 2.0.4 on 2018-05-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField()),
                ('recent_publications', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
    ]
