# Generated by Django 2.0.4 on 2018-05-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField()),
                ('recent_publications', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField()),
                ('recent_publications', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField()),
                ('recent_publications', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField()),
                ('recent_publications', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SKH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField()),
                ('recent_publications', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField()),
                ('recent_publications', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField()),
                ('recent_publications', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField()),
                ('recent_publications', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
    ]
